# config.toml

# Slack Webhook URL for sending alerts
slack_webhook_url = "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"

# PagerDuty
pagerduty_routing_key = "YOUR_PAGERDUTY_API_KEY"

base_path = "/home/ubuntu/hl/data/node_logs/status/hourly"

validator_address = "0xef22f260eec3b7d1edebe53359f5ca584c18d5ac"

#log read interval
check_interval = 10

# SinceLastSuccess
alert_threshold_success = 40.0

# LastAckDuration
alert_threshold_ack = 0.03