# config.toml

# Slack Webhook URL for sending alerts
slack_webhook_url = "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"

# PagerDuty
pagerduty_routing_key = "YOUR_PAGERDUTY_API_KEY"

base_path = "/home/ubuntu/hl/data/node_logs/status/hourly"

validator_address = "0xef22f260eec3b7d1edebe53359f5ca584c18d5ac"

#Decide how often you want to view the logs (1 minute recommended)
check_interval = 60
#If the logs show no updates for 5 minutes, the hl-visor (or consensus) should be considered dead.
log_update_interval = 300

# SinceLastSuccess
alert_threshold_success = 40.0

# LastAckDuration
alert_threshold_ack = 0.03